#!/usr/bin/env python3
"""Generate default reply handlers for unimplemented commands."""

import re
from pathlib import Path

def parse_protocol_file(protocol_path):
    """Parse protocol file to extract Cmd -> Reply mappings."""
    mappings = []

    with open(protocol_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find all command definitions with their reply types
    # Pattern: /// / Original: SomeRequest / SomeReply
    #          SomeCmd = number,
    pattern = r'///\s*/\s*Original:\s*(\w+)\s*/\s*(\w+)\s*\n\s*(\w+Cmd)\s*='

    for match in re.finditer(pattern, content):
        request_type = match.group(1)
        reply_type = match.group(2)
        cmd_name = match.group(3)

        if reply_type.endswith('Reply'):
            mappings.append({
                'cmd': cmd_name,
                'reply': reply_type
            })

    return mappings

def find_actual_type_name(content, type_name):
    """Find the actual struct name in the file (case-sensitive)."""
    # Look for: pub struct TypeName {
    pattern = rf'pub struct ({type_name})\s*{{'
    match = re.search(pattern, content, re.IGNORECASE)
    if match:
        return match.group(1)
    return type_name

def generate_handler_code(mappings, protocol_content):
    """Generate the send_default_reply function code."""
    lines = [
        "pub async fn send_default_reply(",
        "    ctx: Arc<Mutex<ConnectionContext>>,",
        "    req: ClientPacket,",
        "    cmd_id: CmdId,",
        ") -> Result<(), AppError> {",
        "    use sonettobuf::*;",
        "    let mut conn = ctx.lock().await;",
        "",
        "    match cmd_id {"
    ]

    for mapping in mappings:
        cmd = mapping['cmd']
        reply = find_actual_type_name(protocol_content, mapping['reply'])
        lines.append(f"        CmdId::{cmd} => conn.send_reply(cmd_id, {reply}::default(), 0, req.up_tag).await?,")

    lines.extend([
        "        _ => return Err(AppError::Cmd(CmdError::UnhandledCmd(cmd_id))),",
        "    }",
        "",
        "    Ok(())",
        "}"
    ])

    return '\n'.join(lines)

def main():
    project_root = Path(__file__).parent.parent
    protocol_file = project_root / "protocol" / "include" / "_.rs"
    output_file = project_root / "gameserver" / "src" / "network" / "default_handlers.rs"

    print(f"Parsing protocol file: {protocol_file}")

    with open(protocol_file, 'r', encoding='utf-8') as f:
        protocol_content = f.read()

    mappings = parse_protocol_file(protocol_file)
    print(f"Found {len(mappings)} command->reply mappings")

    print(f"Generating handler code...")
    handler_code = generate_handler_code(mappings, protocol_content)

    full_code = f"""// Auto-generated by scripts/generate_default_handlers.py
// DO NOT EDIT MANUALLY

use crate::error::{{AppError, CmdError}};
use crate::network::packet::ClientPacket;
use crate::state::ConnectionContext;
use std::sync::Arc;
use tokio::sync::Mutex;
use sonettobuf::CmdId;

{handler_code}
"""

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(full_code)

    print(f"Generated: {output_file}")
    print(f"Total mappings: {len(mappings)}")

if __name__ == "__main__":
    main()
