// Auto-generated by scripts/gen_effect_enums.py — do not edit manually.
// Target IDs from skill_effect conditionTarget / behaviorTarget fields.

use crate::state::battle::utils::find_entity;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    AllAlly,          // 101
    AllEnemy,         // 102, 202, 301, 302
    Self_,            // 103, 234
    AllAllyNoSelf,    // 104
    RandomAlly,       // 105
    RandomEnemy,      // 106, 107, 108
    LowestHpAlly,     // 109
    HighestExAlly,    // 112
    AdjacentFront,    // 128
    Target_,          // 1, 204, 205, 206, 207, 233
    Attacker,         // 203
    TwoEnemy,         // 201
    MostHpEnemy,      // 208
    EnemyByPosition(i32), // 226-235 (pos = id - 225)
    Other(i32),
}

impl Target {
    pub fn entities(self, fight: &sonettobuf::Fight, owner_uid: i64) -> Vec<i64> {
        self.entities_with_skill_target(fight, owner_uid, 0)
    }

    pub fn entities_with_skill_target(self, fight: &sonettobuf::Fight, owner_uid: i64, skill_target_uid: i64) -> Vec<i64> {
        let side = if owner_uid >= 0 { fight.attacker.as_ref() } else { fight.defender.as_ref() };
        let enemy_side = if owner_uid >= 0 { fight.defender.as_ref() } else { fight.attacker.as_ref() };
        let ally: Vec<i64> = side.map_or(vec![], |s| {
            s.entitys.iter().chain(s.sub_entitys.iter())
                .filter(|e| e.current_hp.unwrap_or(0) > 0)
                .filter_map(|e| e.uid).collect()
        });
        let enemies: Vec<i64> = enemy_side.map_or(vec![], |s| {
            s.entitys.iter().chain(s.sub_entitys.iter())
                .filter(|e| e.current_hp.unwrap_or(0) > 0)
                .filter_map(|e| e.uid).collect()
        });
        match self {
            Target::AllAlly => ally,
            Target::AllEnemy => enemies,
            Target::Self_ => vec![owner_uid],
            Target::AllAllyNoSelf => ally.into_iter().filter(|&uid| uid != owner_uid).collect(),
            Target::Attacker | Target::Target_ => {
                if skill_target_uid != 0 { vec![skill_target_uid] } else { vec![] }
            }
            Target::RandomAlly => ally.first().copied().map(|u| vec![u]).unwrap_or_default(),
            Target::RandomEnemy => enemies.first().copied().map(|u| vec![u]).unwrap_or_default(),
            Target::LowestHpAlly => ally.into_iter()
                .min_by_key(|&uid| {
                    find_entity(fight, uid).map(|e| {
                        let cur = e.current_hp.unwrap_or(0) as f32;
                        let max = e.attr.as_ref().and_then(|a| a.hp).unwrap_or(1) as f32;
                        (cur / max * 10000.0) as i32
                    }).unwrap_or(i32::MAX)
                })
                .map(|u| vec![u]).unwrap_or_default(),
            Target::HighestExAlly => ally.into_iter()
                .max_by_key(|&uid| find_entity(fight, uid).and_then(|e| e.ex_point).unwrap_or(0))
                .map(|u| vec![u]).unwrap_or_else(|| vec![owner_uid]),
            Target::AdjacentFront => {
                let caster_pos = find_entity(fight, owner_uid).and_then(|e| e.position).unwrap_or(0);
                let target_pos = caster_pos - 1;
                if target_pos <= 0 { return vec![]; }
                ally.into_iter()
                    .filter(|&uid| find_entity(fight, uid).and_then(|e| e.position) == Some(target_pos))
                    .collect()
            }
            Target::TwoEnemy => {
                if enemies.is_empty() { return vec![]; }
                let primary = if enemies.contains(&skill_target_uid) { skill_target_uid } else { enemies[0] };
                let mut out = vec![primary];
                if enemies.len() > 1 {
                    let idx = enemies.iter().position(|&u| u == primary).unwrap_or(0);
                    let extra = enemies[(idx + 1) % enemies.len()];
                    if extra != primary { out.push(extra); }
                }
                out
            }
            Target::MostHpEnemy => enemies.into_iter()
                .max_by_key(|&uid| find_entity(fight, uid).and_then(|e| e.current_hp).unwrap_or(0))
                .map(|u| vec![u]).unwrap_or_default(),
            Target::EnemyByPosition(pos) => enemies.into_iter()
                .filter(|&uid| find_entity(fight, uid).and_then(|e| e.position) == Some(pos))
                .collect(),
            other => {
                tracing::warn!("unimplemented target variant: {:?}", other);
                vec![]
            }
        }
    }

    pub fn from_id(id: i32) -> Self {
        match id {
            101 => Target::AllAlly,
            102 | 202 | 301 | 302 => Target::AllEnemy,
            103 | 234 => Target::Self_,
            104 => Target::AllAllyNoSelf,
            105 => Target::RandomAlly,
            106 | 107 | 108 => Target::RandomEnemy,
            109 => Target::LowestHpAlly,
            112 => Target::HighestExAlly,
            128 => Target::AdjacentFront,
            203 => Target::Attacker,
            201 => Target::TwoEnemy,
            208 => Target::MostHpEnemy,
            226..=235 => Target::EnemyByPosition(id - 225),
            0 | 1 | 204 | 205 | 206 | 207 | 233 => Target::Target_,
            v => Target::Other(v),
        }
    }
}
